name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build sdist and wheel
        run: python -m build

      - name: Inspect wheel metadata
        run: |
          python - << 'PY'
          import zipfile, glob
          for p in glob.glob('dist/*.whl'):
              print('Inspecting', p)
              with zipfile.ZipFile(p) as z:
                  meta = [n for n in z.namelist() if n.endswith('METADATA')]
                  print('META files:', meta)
                  if meta:
                      data = z.read(meta[0]).decode('utf-8', errors='replace')
                      print('\n'.join(data.splitlines()[:30]))
          PY

      - name: Upload to PyPI with twine
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          python -m twine check dist/*
          python -m twine upload dist/*

